import { MigrationInterface, QueryRunner } from "typeorm";

export class InsertCountriesMainAdmin1663931160470 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (1, 'AF', 'Afghanistan', 93, 'Afghan afghani', 'Ø‹', 'AFN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (2, 'AL', 'Albania', 355, 'Albanian lek', 'L', 'ALL');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (3, 'DZ', 'Algeria', 213, 'Algerian dinar', 'Ø¯.Ø¬', 'DZD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (4, 'AS', 'American Samoa', 1684, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (5, 'AD', 'Andorra', 376, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (6, 'AO', 'Angola', 244, 'Angolan kwanza', 'Kz', 'AOA');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (7, 'AI', 'Anguilla', 1264, 'East Caribbean dolla', '$', 'XCD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (8, 'AQ', 'Antarctica', 0, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (9, 'AG', 'Antigua And Barbuda', 1268, 'East Caribbean dolla', '$', 'XCD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (10, 'AR', 'Argentina', 54, 'Argentine peso', '$', 'ARS');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (11, 'AM', 'Armenia', 374, 'Armenian dram', '', 'AMD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (12, 'AW', 'Aruba', 297, 'Aruban florin', 'Æ’', 'AWG');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (13, 'AU', 'Australia', 61, 'Australian dollar', '$', 'AUD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (14, 'AT', 'Austria', 43, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (15, 'AZ', 'Azerbaijan', 994, 'Azerbaijani manat', '', 'AZN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (16, 'BS', 'Bahamas The', 1242, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (17, 'BH', 'Bahrain', 973, 'Bahraini dinar', '.Ø¯.Ø¨', 'BHD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (18, 'BD', 'Bangladesh', 880, 'Bangladeshi taka', 'à§³', 'BDT');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (19, 'BB', 'Barbados', 1246, 'Barbadian dollar', '$', 'BBD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (20, 'BY', 'Belarus', 375, 'Belarusian ruble', 'Br', 'BYR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (21, 'BE', 'Belgium', 32, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (22, 'BZ', 'Belize', 501, 'Belize dollar', '$', 'BZD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (23, 'BJ', 'Benin', 229, 'West African CFA fra', 'Fr', 'XOF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (24, 'BM', 'Bermuda', 1441, 'Bermudian dollar', '$', 'BMD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (25, 'BT', 'Bhutan', 975, 'Bhutanese ngultrum', 'Nu.', 'BTN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (26, 'BO', 'Bolivia', 591, 'Bolivian boliviano', 'Bs.', 'BOB');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (27, 'BA', 'Bosnia and Herzegovina', 387, 'Bosnia and Herzegovi', 'KM or ÐšÐœ', 'BAM');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (28, 'BW', 'Botswana', 267, 'Botswana pula', 'P', 'BWP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (29, 'BV', 'Bouvet Island', 0, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (30, 'BR', 'Brazil', 55, 'Brazilian real', 'R$', 'BRL');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (31, 'IO', 'British Indian Ocean Territory', 246, 'United States dollar', '$', 'USD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (32, 'BN', 'Brunei', 673, 'Brunei dollar', '$', 'BND');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (33, 'BG', 'Bulgaria', 359, 'Bulgarian lev', 'Ð»Ð²', 'BGN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (34, 'BF', 'Burkina Faso', 226, 'West African CFA fra', 'Fr', 'XOF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (35, 'BI', 'Burundi', 257, 'Burundian franc', 'Fr', 'BIF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (36, 'KH', 'Cambodia', 855, 'Cambodian riel', 'áŸ›', 'KHR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (37, 'CM', 'Cameroon', 237, 'Central African CFA ', 'Fr', 'XAF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (38, 'CA', 'Canada', 1, 'Canadian dollar', '$', 'CAD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (39, 'CV', 'Cape Verde', 238, 'Cape Verdean escudo', 'Esc or $', 'CVE');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (40, 'KY', 'Cayman Islands', 1345, 'Cayman Islands dolla', '$', 'KYD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (41, 'CF', 'Central African Republic', 236, 'Central African CFA ', 'Fr', 'XAF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (42, 'TD', 'Chad', 235, 'Central African CFA ', 'Fr', 'XAF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (43, 'CL', 'Chile', 56, 'Chilean peso', '$', 'CLP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (44, 'CN', 'China', 86, 'Chinese yuan', 'Â¥ or å…ƒ', 'CNY');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (45, 'CX', 'Christmas Island', 61, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (46, 'CC', 'Cocos (Keeling) Islands', 672, 'Australian dollar', '$', 'AUD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (47, 'CO', 'Colombia', 57, 'Colombian peso', '$', 'COP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (48, 'KM', 'Comoros', 269, 'Comorian franc', 'Fr', 'KMF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (49, 'CG', 'Congo', 242, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (50, 'CD', 'Congo The Democratic Republic Of The', 242, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (51, 'CK', 'Cook Islands', 682, 'New Zealand dollar', '$', 'NZD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (52, 'CR', 'Costa Rica', 506, 'Costa Rican colÃ³n', 'â‚¡', 'CRC');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (53, 'CI', 'Cote D''Ivoire (Ivory Coast)', 225, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (54, 'HR', 'Croatia (Hrvatska)', 385, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (55, 'CU', 'Cuba', 53, 'Cuban convertible pe', '$', 'CUC');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (56, 'CY', 'Cyprus', 357, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (57, 'CZ', 'Czech Republic', 420, 'Czech koruna', 'KÄ', 'CZK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (58, 'DK', 'Denmark', 45, 'Danish krone', 'kr', 'DKK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (59, 'DJ', 'Djibouti', 253, 'Djiboutian franc', 'Fr', 'DJF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (60, 'DM', 'Dominica', 1767, 'East Caribbean dolla', '$', 'XCD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (61, 'DO', 'Dominican Republic', 1809, 'Dominican peso', '$', 'DOP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (62, 'TP', 'East Timor', 670, 'United States dollar', '$', 'USD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (63, 'EC', 'Ecuador', 593, 'United States dollar', '$', 'USD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (64, 'EG', 'Egypt', 20, 'Egyptian pound', 'Â£ or Ø¬.Ù…', 'EGP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (65, 'SV', 'El Salvador', 503, 'United States dollar', '$', 'USD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (66, 'GQ', 'Equatorial Guinea', 240, 'Central African CFA ', 'Fr', 'XAF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (67, 'ER', 'Eritrea', 291, 'Eritrean nakfa', 'Nfk', 'ERN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (68, 'EE', 'Estonia', 372, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (69, 'ET', 'Ethiopia', 251, 'Ethiopian birr', 'Br', 'ETB');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (70, 'XA', 'External Territories of Australia', 61, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (71, 'FK', 'Falkland Islands', 500, 'Falkland Islands pou', 'Â£', 'FKP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (72, 'FO', 'Faroe Islands', 298, 'Danish krone', 'kr', 'DKK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (73, 'FJ', 'Fiji Islands', 679, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (74, 'FI', 'Finland', 358, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (75, 'FR', 'France', 33, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (76, 'GF', 'French Guiana', 594, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (77, 'PF', 'French Polynesia', 689, 'CFP franc', 'Fr', 'XPF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (78, 'TF', 'French Southern Territories', 0, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (79, 'GA', 'Gabon', 241, 'Central African CFA ', 'Fr', 'XAF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (80, 'GM', 'Gambia The', 220, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (81, 'GE', 'Georgia', 995, 'Georgian lari', 'áƒš', 'GEL');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (82, 'DE', 'Germany', 49, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (83, 'GH', 'Ghana', 233, 'Ghana cedi', 'â‚µ', 'GHS');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (84, 'GI', 'Gibraltar', 350, 'Gibraltar pound', 'Â£', 'GIP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (85, 'GR', 'Greece', 30, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (86, 'GL', 'Greenland', 299, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (87, 'GD', 'Grenada', 1473, 'East Caribbean dolla', '$', 'XCD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (88, 'GP', 'Guadeloupe', 590, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (89, 'GU', 'Guam', 1671, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (90, 'GT', 'Guatemala', 502, 'Guatemalan quetzal', 'Q', 'GTQ');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (91, 'XU', 'Guernsey and Alderney', 44, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (92, 'GN', 'Guinea', 224, 'Guinean franc', 'Fr', 'GNF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (93, 'GW', 'Guinea-Bissau', 245, 'West African CFA fra', 'Fr', 'XOF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (94, 'GY', 'Guyana', 592, 'Guyanese dollar', '$', 'GYD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (95, 'HT', 'Haiti', 509, 'Haitian gourde', 'G', 'HTG');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (96, 'HM', 'Heard and McDonald Islands', 0, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (97, 'HN', 'Honduras', 504, 'Honduran lempira', 'L', 'HNL');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (98, 'HK', 'Hong Kong S.A.R.', 852, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (99, 'HU', 'Hungary', 36, 'Hungarian forint', 'Ft', 'HUF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (100, 'IS', 'Iceland', 354, 'Icelandic krÃ³na', 'kr', 'ISK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (101, 'IN', 'India', 91, 'Indian rupee', 'â‚¹', 'INR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (102, 'ID', 'Indonesia', 62, 'Indonesian rupiah', 'Rp', 'IDR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (103, 'IR', 'Iran', 98, 'Iranian rial', 'ï·¼', 'IRR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (104, 'IQ', 'Iraq', 964, 'Iraqi dinar', 'Ø¹.Ø¯', 'IQD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (105, 'IE', 'Ireland', 353, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (106, 'IL', 'Israel', 972, 'Israeli new shekel', 'â‚ª', 'ILS');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (107, 'IT', 'Italy', 39, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (108, 'JM', 'Jamaica', 1876, 'Jamaican dollar', '$', 'JMD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (109, 'JP', 'Japan', 81, 'Japanese yen', 'Â¥', 'JPY');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (110, 'XJ', 'Jersey', 44, 'British pound', 'Â£', 'GBP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (111, 'JO', 'Jordan', 962, 'Jordanian dinar', 'Ø¯.Ø§', 'JOD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (112, 'KZ', 'Kazakhstan', 7, 'Kazakhstani tenge', '', 'KZT');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (113, 'KE', 'Kenya', 254, 'Kenyan shilling', 'Sh', 'KES');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (114, 'KI', 'Kiribati', 686, 'Australian dollar', '$', 'AUD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (115, 'KP', 'Korea North', 850, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (116, 'KR', 'Korea South', 82, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (117, 'KW', 'Kuwait', 965, 'Kuwaiti dinar', 'Ø¯.Ùƒ', 'KWD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (118, 'KG', 'Kyrgyzstan', 996, 'Kyrgyzstani som', 'Ð»Ð²', 'KGS');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (119, 'LA', 'Laos', 856, 'Lao kip', 'â‚­', 'LAK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (120, 'LV', 'Latvia', 371, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (121, 'LB', 'Lebanon', 961, 'Lebanese pound', 'Ù„.Ù„', 'LBP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (122, 'LS', 'Lesotho', 266, 'Lesotho loti', 'L', 'LSL');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (123, 'LR', 'Liberia', 231, 'Liberian dollar', '$', 'LRD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (124, 'LY', 'Libya', 218, 'Libyan dinar', 'Ù„.Ø¯', 'LYD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (125, 'LI', 'Liechtenstein', 423, 'Swiss franc', 'Fr', 'CHF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (126, 'LT', 'Lithuania', 370, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (127, 'LU', 'Luxembourg', 352, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (128, 'MO', 'Macau S.A.R.', 853, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (129, 'MK', 'Macedonia', 389, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (130, 'MG', 'Madagascar', 261, 'Malagasy ariary', 'Ar', 'MGA');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (131, 'MW', 'Malawi', 265, 'Malawian kwacha', 'MK', 'MWK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (132, 'MY', 'Malaysia', 60, 'Malaysian ringgit', 'RM', 'MYR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (133, 'MV', 'Maldives', 960, 'Maldivian rufiyaa', '.Þƒ', 'MVR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (134, 'ML', 'Mali', 223, 'West African CFA fra', 'Fr', 'XOF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (135, 'MT', 'Malta', 356, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (136, 'XM', 'Man (Isle of)', 44, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (137, 'MH', 'Marshall Islands', 692, 'United States dollar', '$', 'USD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (138, 'MQ', 'Martinique', 596, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (139, 'MR', 'Mauritania', 222, 'Mauritanian ouguiya', 'UM', 'MRO');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (140, 'MU', 'Mauritius', 230, 'Mauritian rupee', 'â‚¨', 'MUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (141, 'YT', 'Mayotte', 269, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (142, 'MX', 'Mexico', 52, 'Mexican peso', '$', 'MXN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (143, 'FM', 'Micronesia', 691, 'Micronesian dollar', '$', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (144, 'MD', 'Moldova', 373, 'Moldovan leu', 'L', 'MDL');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (145, 'MC', 'Monaco', 377, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (146, 'MN', 'Mongolia', 976, 'Mongolian tÃ¶grÃ¶g', 'â‚®', 'MNT');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (147, 'MS', 'Montserrat', 1664, 'East Caribbean dolla', '$', 'XCD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (148, 'MA', 'Morocco', 212, 'Moroccan dirham', 'Ø¯.Ù….', 'MAD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (149, 'MZ', 'Mozambique', 258, 'Mozambican metical', 'MT', 'MZN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (150, 'MM', 'Myanmar', 95, 'Burmese kyat', 'Ks', 'MMK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (151, 'NA', 'Namibia', 264, 'Namibian dollar', '$', 'NAD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (152, 'NR', 'Nauru', 674, 'Australian dollar', '$', 'AUD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (153, 'NP', 'Nepal', 977, 'Nepalese rupee', 'â‚¨', 'NPR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (154, 'AN', 'Netherlands Antilles', 599, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (155, 'NL', 'Netherlands The', 31, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (156, 'NC', 'New Caledonia', 687, 'CFP franc', 'Fr', 'XPF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (157, 'NZ', 'New Zealand', 64, 'New Zealand dollar', '$', 'NZD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (158, 'NI', 'Nicaragua', 505, 'Nicaraguan cÃ³rdoba', 'C$', 'NIO');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (159, 'NE', 'Niger', 227, 'West African CFA fra', 'Fr', 'XOF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (160, 'NG', 'Nigeria', 234, 'Nigerian naira', 'â‚¦', 'NGN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (161, 'NU', 'Niue', 683, 'New Zealand dollar', '$', 'NZD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (162, 'NF', 'Norfolk Island', 672, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (163, 'MP', 'Northern Mariana Islands', 1670, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (164, 'NO', 'Norway', 47, 'Norwegian krone', 'kr', 'NOK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (165, 'OM', 'Oman', 968, 'Omani rial', 'Ø±.Ø¹.', 'OMR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (166, 'PK', 'Pakistan', 92, 'Pakistani rupee', 'â‚¨', 'PKR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (167, 'PW', 'Palau', 680, 'Palauan dollar', '$', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (168, 'PS', 'Palestinian Territory Occupied', 970, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (169, 'PA', 'Panama', 507, 'Panamanian balboa', 'B/.', 'PAB');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (170, 'PG', 'Papua new Guinea', 675, 'Papua New Guinean ki', 'K', 'PGK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (171, 'PY', 'Paraguay', 595, 'Paraguayan guaranÃ­', 'â‚²', 'PYG');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (172, 'PE', 'Peru', 51, 'Peruvian nuevo sol', 'S/.', 'PEN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (173, 'PH', 'Philippines', 63, 'Philippine peso', '₱', 'PHP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (174, 'PN', 'Pitcairn Island', 0, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (175, 'PL', 'Poland', 48, 'Polish zÅ‚oty', 'zÅ‚', 'PLN');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (176, 'PT', 'Portugal', 351, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (177, 'PR', 'Puerto Rico', 1787, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (178, 'QA', 'Qatar', 974, 'Qatari riyal', 'Ø±.Ù‚', 'QAR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (179, 'RE', 'Reunion', 262, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (180, 'RO', 'Romania', 40, 'Romanian leu', 'lei', 'RON');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (181, 'RU', 'Russia', 70, 'Russian ruble', '', 'RUB');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (182, 'RW', 'Rwanda', 250, 'Rwandan franc', 'Fr', 'RWF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (183, 'SH', 'Saint Helena', 290, 'Saint Helena pound', 'Â£', 'SHP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (184, 'KN', 'Saint Kitts And Nevis', 1869, 'East Caribbean dolla', '$', 'XCD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (185, 'LC', 'Saint Lucia', 1758, 'East Caribbean dolla', '$', 'XCD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (186, 'PM', 'Saint Pierre and Miquelon', 508, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (187, 'VC', 'Saint Vincent And The Grenadines', 1784, 'East Caribbean dolla', '$', 'XCD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (188, 'WS', 'Samoa', 684, 'Samoan tÄlÄ', 'T', 'WST');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (189, 'SM', 'San Marino', 378, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (190, 'ST', 'Sao Tome and Principe', 239, 'SÃ£o TomÃ© and PrÃ­ncip', 'Db', 'STD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (191, 'SA', 'Saudi Arabia', 966, 'Saudi riyal', 'Ø±.Ø³', 'SAR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (192, 'SN', 'Senegal', 221, 'West African CFA fra', 'Fr', 'XOF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (193, 'RS', 'Serbia', 381, 'Serbian dinar', 'Ð´Ð¸Ð½. or din.', 'RSD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (194, 'SC', 'Seychelles', 248, 'Seychellois rupee', 'â‚¨', 'SCR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (195, 'SL', 'Sierra Leone', 232, 'Sierra Leonean leone', 'Le', 'SLL');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (196, 'SG', 'Singapore', 65, 'Brunei dollar', '$', 'BND');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (197, 'SK', 'Slovakia', 421, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (198, 'SI', 'Slovenia', 386, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (199, 'XG', 'Smaller Territories of the UK', 44, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (200, 'SB', 'Solomon Islands', 677, 'Solomon Islands doll', '$', 'SBD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (201, 'SO', 'Somalia', 252, 'Somali shilling', 'Sh', 'SOS');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (202, 'ZA', 'South Africa', 27, 'South African rand', 'R', 'ZAR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (203, 'GS', 'South Georgia', 0, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (204, 'SS', 'South Sudan', 211, 'South Sudanese pound', 'Â£', 'SSP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (205, 'ES', 'Spain', 34, 'Euro', 'â‚¬', 'EUR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (206, 'LK', 'Sri Lanka', 94, 'Sri Lankan rupee', 'Rs or à¶»à·”', 'LKR');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (207, 'SD', 'Sudan', 249, 'Sudanese pound', 'Ø¬.Ø³.', 'SDG');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (208, 'SR', 'Suriname', 597, 'Surinamese dollar', '$', 'SRD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (209, 'SJ', 'Svalbard And Jan Mayen Islands', 47, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (210, 'SZ', 'Swaziland', 268, 'Swazi lilangeni', 'L', 'SZL');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (211, 'SE', 'Sweden', 46, 'Swedish krona', 'kr', 'SEK');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (212, 'CH', 'Switzerland', 41, 'Swiss franc', 'Fr', 'CHF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (213, 'SY', 'Syria', 963, 'Syrian pound', 'Â£ or Ù„.Ø³', 'SYP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (214, 'TW', 'Taiwan', 886, 'New Taiwan dollar', '$', 'TWD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (215, 'TJ', 'Tajikistan', 992, 'Tajikistani somoni', 'Ð…Ðœ', 'TJS');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (216, 'TZ', 'Tanzania', 255, 'Tanzanian shilling', 'Sh', 'TZS');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (217, 'TH', 'Thailand', 66, 'Thai baht', 'à¸¿', 'THB');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (218, 'TG', 'Togo', 228, 'West African CFA fra', 'Fr', 'XOF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (219, 'TK', 'Tokelau', 690, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (220, 'TO', 'Tonga', 676, 'Tongan paÊ»anga', 'T$', 'TOP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (221, 'TT', 'Trinidad And Tobago', 1868, 'Trinidad and Tobago ', '$', 'TTD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (222, 'TN', 'Tunisia', 216, 'Tunisian dinar', 'Ø¯.Øª', 'TND');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (223, 'TR', 'Turkey', 90, 'Turkish lira', '', 'TRY');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (224, 'TM', 'Turkmenistan', 7370, 'Turkmenistan manat', 'm', 'TMT');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (225, 'TC', 'Turks And Caicos Islands', 1649, 'United States dollar', '$', 'USD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (226, 'TV', 'Tuvalu', 688, 'Australian dollar', '$', 'AUD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (227, 'UG', 'Uganda', 256, 'Ugandan shilling', 'Sh', 'UGX');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (228, 'UA', 'Ukraine', 380, 'Ukrainian hryvnia', 'â‚´', 'UAH');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (229, 'AE', 'United Arab Emirates', 971, 'United Arab Emirates', 'Ø¯.Ø¥', 'AED');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (230, 'GB', 'United Kingdom', 44, 'British pound', 'Â£', 'GBP');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (231, 'US', 'United States', 1, 'United States dollar', '$', 'USD');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (232, 'UM', 'United States Minor Outlying Islands', 1, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (233, 'UY', 'Uruguay', 598, 'Uruguayan peso', '$', 'UYU');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (234, 'UZ', 'Uzbekistan', 998, 'Uzbekistani som', '', 'UZS');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (235, 'VU', 'Vanuatu', 678, 'Vanuatu vatu', 'Vt', 'VUV');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (236, 'VA', 'Vatican City State (Holy See)', 39, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (237, 'VE', 'Venezuela', 58, 'Venezuelan bolÃ­var', 'Bs F', 'VEF');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (238, 'VN', 'Vietnam', 84, 'Vietnamese Ä‘á»“ng', 'â‚«', 'VND');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (239, 'VG', 'Virgin Islands (British)', 1284, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (240, 'VI', 'Virgin Islands (US)', 1340, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (241, 'WF', 'Wallis And Futuna Islands', 681, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (242, 'EH', 'Western Sahara', 212, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (243, 'YE', 'Yemen', 967, 'Yemeni rial', 'ï·¼', 'YER');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (244, 'YU', 'Yugoslavia', 38, '', '', '');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (245, 'ZM', 'Zambia', 260, 'Zambian kwacha', 'ZK', 'ZMW');
insert into countries (pk, code, name, dial_code, currency_name, currency_symbol, currency_code) values (246, 'ZW', 'Zimbabwe', 263, 'Botswana pula', 'P', 'BWP');
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            delete from countries;
        `);
    }

}
